name: nexus

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: unless-stopped