export const NEW_MESSAGE_EVENT ="NEW_MESSAGE_EVENT"
export const NEW_MESSAGE_ALERT ="NEW_MESSAGE_ALERT"

export const CONNECTED_EVENT = "CONNECTED_EVENT"
export const DISCONNECT_EVENT = "DISCONNECT_EVENT"


export const JOIN_CHAT_EVENT ="JOIN_CHAT_EVENT"
export const LEAVE_CHAT_EVENT ="LEAVE_CHAT_EVENT"
export const NEW_CHAT_EVENT = "NEW_CHAT_EVENT"
export const TYPING = "TYPING"
export const TOGGLE_REACTION_EVENT = "TOGGLE_REACTION_EVENT"
export const USER_ONLINE_EVENT = "USER_ONLINE_EVENT"
export const USER_OFFLINE_EVENT = "USER_OFFLINE_EVENT"
export const CHECK_ONLINE_EVENT = "CHECK_ONLINE_EVENT"


